DFPlayerEDU.setVol(10)
serial.writeLine("VOL:" + DFPlayerEDU.getVol())
DFPlayerEDU.switchFunction(eWorkPattern.MUSIC)
DFPlayerEDU.setPlayMode(ePlayMode.ALLCYCLE)
serial.writeLine("PlayMode:" + DFPlayerEDU.getPlayMode())
serial.writeLine("Statr playing")
DFPlayerEDU.setPlayState(ePlayState.START)
basic.pause(10000)
serial.writeLine("Pause")
DFPlayerEDU.setPlayState(ePlayState.PAUSE)
basic.pause(10000)
serial.writeLine("Next")
DFPlayerEDU.songChoice(eSongChoice.NEXT)
basic.pause(10000)
serial.writeLine("Previous")
DFPlayerEDU.songChoice(eSongChoice.LAST)
basic.pause(10000)
serial.writeLine("Statr playing")
DFPlayerEDU.fastForwardOrReverse(eDirection.FORWARD, 10)
serial.writeLine("File number:" + DFPlayerEDU.getData(eData.FILENUMBER))
serial.writeLine("The number of files available to play:" + DFPlayerEDU.getData(eData.TOTALFILE))
serial.writeLine("The time length the current song has played:" + DFPlayerEDU.getData(eData.CURTIME))
serial.writeLine("The total length of the currently-playing song: " + DFPlayerEDU.getData(eData.TOTALTIME))
serial.writeLine("The name of the currently-playing file:" + DFPlayerEDU.getFileName())
basic.pause(10000)
DFPlayerEDU.playFileNum(1)
